/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import java.io.*;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        var app = new App();
        var stream = new ByteArrayOutputStream();
        app.printExampleProgram(stream);
        assertNotEquals("", new String(stream.toByteArray()));
    }
}
