/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import java.io.*;
import org.junit.Test;
// import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() throws IOException {
        var ast = App.readAndParse("./examples/example3.bg");
        App.check(ast);
    }
}
